version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - ./:/usr/src/app
    networks:
      - adv-top

networks:
  adv-top: {}
